name: Flask CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Flask app (optional)
        run: |
          echo "Add test commands here"
      - name: Deploy (example)
        run: |
          echo "Trigger deployment here or integrate with Railway CLI, Render or Docker push"